### ISSUE TITLE
Lint to make sure that all tscircuit dependencies are either devDependencies or peerDependencies (not listed in `dependencies`)

### ISSUE THREAD

**Issue by seveibar** [tscircuit/lint#4]
This fixes a wide host of issues when using working with modules where they accidentally get doubled:

![Image](https://github.com/user-attachments/assets/fc162836-54dd-4105-83f1-ab6ae2f4e887)

/bounty $10

**Comment by seveibar** [comment]
CC @ShiboSoftwareDev this would have saved you a few headaches i'd guess 😁

**Comment by seveibar** [comment]
also when added as a peerDependency:

- they must also have a devDependency
- they must be a "*"

![Image](https://github.com/user-attachments/assets/9676bba3-c934-4228-bda6-987fc847957a)

**Comment by seveibar** [comment]
The following types of dependencies are considered tscircuit dependencies:

        "@tscircuit/*",
        "circuit-to-svg",
        "jscad-fiber",
        "jscad-electronics",
        "circuit-json",
        "dsn-converter",
        "circuit-json-to-*"

**Comment by Abse2001** [comment]
/attempt #4

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Abse2001) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Abse2001 | 19 tscircuit bounties | <div align="center">TypeScript</div> | <div align="center">﹟476</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm53aaa8v000fmk03wv8uwbpt/cancel-attempt) |

**Comment by Anshgrover23** [comment]
/attempt #4

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Anshgrover23) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Anshgrover23 | &nbsp;&nbsp;&nbsp;18 tscircuit bounties <br/> + 3 bounties from 3 projects | <div align="center">TypeScript, JavaScript, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm53aaa8v000fmk03wv8uwbpt/cancel-attempt) |
